#!/usr/bin/python3.11

import sys, os
from beavor.MainWindow import MainWindow
from beavor.backend import DatabaseManager

DEFAULT_DATABASE_PATH = "worklist.db"

def main():
  beavor: MainWindow
  if len(sys.argv) > 1:
    beavor = MainWindow(sys.argv[1])
  elif os.path.isfile(DEFAULT_DATABASE_PATH):
    #default
    beavor = MainWindow(DEFAULT_DATABASE_PATH)
  else:
    print(f"No database found and none specified.\nCreating new {DEFAULT_DATABASE_PATH}")
    DatabaseManager.create_new_database(DEFAULT_DATABASE_PATH)
    beavor = MainWindow(DEFAULT_DATABASE_PATH)

  beavor.root.mainloop()

if __name__ == "__main__":
  main()
