#!/usr/bin/python3.11

import sys, os
from beavor.MainWindow import MainWindow, Settings
from beavor.backend import DatabaseManager

DEFAULT_DATABASE_PATH = "worklist.db"
DEFAULT_SETTINGS_PATH = "settings.json"

def main():
    beavor: MainWindow

    # Create settings file if it doesn't exist
    if not os.path.isfile(DEFAULT_SETTINGS_PATH):
        Settings.create_new(DEFAULT_SETTINGS_PATH)

    if len(sys.argv) > 1:
        beavor = MainWindow(sys.argv[1], DEFAULT_SETTINGS_PATH)
    elif os.path.isfile(DEFAULT_DATABASE_PATH):
        #default
        beavor = MainWindow(DEFAULT_DATABASE_PATH, DEFAULT_SETTINGS_PATH)
    else:
        print(f"No database found and none specified.\nCreating new {DEFAULT_DATABASE_PATH}")
        DatabaseManager.create_new_database(DEFAULT_DATABASE_PATH)
        beavor = MainWindow(DEFAULT_DATABASE_PATH, DEFAULT_SETTINGS_PATH)

    beavor.root.mainloop()

if __name__ == "__main__":
    main()
